services:
  jenkins:
    build:
      context: .
      dockerfile: Jenkins.Dockerfile
    container_name: jenkins-frontend
    user: root
    privileged: true
    ports:
      - "8087:8080"
      - "50007:50000"
    volumes:
      - jenkins_home_frontend:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - jenkins-frontend-net
    restart: unless-stopped

  selenium:
    image: seleniarm/standalone-chromium:latest
    container_name: selenium
    shm_size: 2g
    ports:
      - "4444:4444"
      - "7900:7900"  # VNC
    networks:
      - jenkins-frontend-net

  # Ce conteneur utilise votre Dockerfile existant
  angular-test:
    build:
      context: .
      target: development  # Utilise le target 'development' de votre Dockerfile multi-stage
    container_name: angular-test
    ports:
      - "4201:4200"
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - jenkins-frontend-net
    command: ["tail", "-f", "/dev/null"]

networks:
  jenkins-frontend-net:
    driver: bridge

volumes:
  jenkins_home_frontend:
